version: 2.1
orbs:
  dmz: eddiewebb/dmz@0.0.7
jobs:
  build:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: "Supersecretpassword123!"
    steps:
      - checkout
